name: Build and Push HomeChat Addon

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: kebabmane

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ["aarch64", "amd64"]
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch the main homechat repository to build the Rails app
          repository: kebabmane/homechat
          path: homechat

      - name: Checkout addon repository
        uses: actions/checkout@v4
        with:
          path: addon

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}/${{ matrix.arch }}-addon-homechat
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set platform variables
        id: platform
        run: |
          case "${{ matrix.arch }}" in
            "amd64")
              echo "docker_platform=linux/amd64" >> $GITHUB_OUTPUT
              echo "arch=amd64" >> $GITHUB_OUTPUT
              echo "build_from=ghcr.io/home-assistant/amd64-base:3.19" >> $GITHUB_OUTPUT
              ;;
            "aarch64")
              echo "docker_platform=linux/arm64" >> $GITHUB_OUTPUT
              echo "arch=aarch64" >> $GITHUB_OUTPUT
              echo "build_from=ghcr.io/home-assistant/aarch64-base:3.19" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: addon/homechat/Dockerfile
          platforms: ${{ steps.platform.outputs.docker_platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_FROM=${{ steps.platform.outputs.build_from }}
            BUILD_ARCH=${{ steps.platform.outputs.arch }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_DESCRIPTION=HomeChat Home Assistant Addon
            BUILD_NAME=HomeChat
            BUILD_REF=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}